; PlatformIO Project Configuration
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0


; Libraries
lib_deps =
    ; Add sensor libraries here as needed
    ; e.g. adafruit/Adafruit Unified Sensor
    ; e.g. adafruit/DHT sensor library
